name: Continuous Integration

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test Library

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Run tests
        run: npm test
