name: Deploy Docs & Run Tests

on:
  push:
    branches: [ main ]

jobs:
  # This job runs your test suite
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js v20
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  # This job deploys your docs to GitHub Pages
  deploy-docs:
    name: Deploy Docs to Pages
    needs: test # This job will only run if the 'test' job succeeds
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions it needs to deploy to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js v20
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'

      - name: Install, Build Library, and Build Docs
        run: |
          npm ci
          npm run build
          npm run docs:build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4